version: '3'
services:
  webapp:
    build: .
    volumes: 
    - .:/webapp
    ports:
    - 3000:3000
    command: sh /webapp/scripts/startup.sh
    links:
    - db
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456